// constants/esmaData.ts

export const ESMA_UL_HUSNA = [
  { id: '1', arabic: 'اللَّهُ', name: 'Allah', meaning: 'Tek yaratıcının özel ismi, varlığı zorunlu olan, bütün kemâl sıfatları kendisinde toplayan hakiki ma\'bûd.' },
{ id: '2', arabic: 'الرَّحْمنُ', name: 'Er-Rahmân', meaning: 'Sonsuz merhametiyle lütuf ve ihsanda bulunan.' },
{ id: '3', arabic: 'الرَّحِيمُ', name: 'Er-Rahîm', meaning: 'Rahmetiyle her şeyi kuşatan.' },
{ id: '4', arabic: 'الْمَلِكُ', name: 'El-Melik', meaning: 'Bütün varlıkların sahibi/hükümdârı.' },
{ id: '5', arabic: 'الْقُدُّوسُ', name: 'El-Kuddûs', meaning: 'Eksiklik ve kusurlardan münezzeh/uzak olan, bütün kemâl sıfatları kendisinde toplayan.' },
{ id: '6', arabic: 'السَّلاَمُ', name: 'Es-Selâm', meaning: 'Esenlik ve selâmet veren, yaratılmışlara özgü değişikliklerden ve yok oluştan münezzeh olan.' },
{ id: '7', arabic: 'الْمُؤْمِنُ', name: 'El-Mü\'min', meaning: 'Bütün mahlûkâta emniyet/güven veren ve kendisine güvenilen.' },
{ id: '8', arabic: 'الْمُهَيْمِنُ', name: 'El-Müheymin', meaning: 'Kâinatın bütün işlerini gözetip yöneten, her şeyi hükmü altına alan.' },
{ id: '9', arabic: 'الْعَزِيزُ', name: 'El-Azîz', meaning: 'Ulu, galip, her şeye üstün gelen izzet sahibi.' },
{ id: '10', arabic: 'الْجَبَّارُ', name: 'El-Cebbâr', meaning: 'Dilediğini yaptırma gücüne sahip olan, her şeyi tasarrufu altına alan ve irâdesini her durumda yürüten.' },
{ id: '11', arabic: 'الْمُتَكَبِّرُ', name: 'El-Mütekebbir', meaning: 'Büyüklüğünü izhar eden, son derece ulu, yüce.' },
{ id: '12', arabic: 'الْخَالِقُ', name: 'El-Hâlik', meaning: 'Her şeyin yaratıcısı, hikmeti gereği her şeyi ölçülü yaratan.' },
{ id: '13', arabic: 'الْبَارِئُ', name: 'El-Bâri\'', meaning: 'Yoktan yaratan, maddesi ve örneği olmadan îcat eden.' },
{ id: '14', arabic: 'الْمُصَوِّرُ', name: 'El-Musavvir', meaning: 'Varlığa şekil ve sûret veren.' },
{ id: '15', arabic: 'الْغَفَّارُ', name: 'El-Gaffâr', meaning: 'Kusur ve günahları örten, çokça bağışlayan.' },
{ id: '16', arabic: 'الْقَهَّارُ', name: 'El-Kahhâr', meaning: 'Yenilmeyen, dilediğini yerine getiren, kendisine her şeyin boyun eğdiği yegâne kudret ve tasarruf sahibi.' },
{ id: '17', arabic: 'الْوَهَّابُ', name: 'El-Vehhâb', meaning: 'Karşılıksız olarak çokça nimet veren ve ihsanda bulunan.' },
{ id: '18', arabic: 'الرَّزَّاقُ', name: 'Er-Rezzâk', meaning: 'Maddî ve manevî bol rızık veren, her türlü rızık imkânlarını yaratan.' },
{ id: '19', arabic: 'الْفَتَّاحُ', name: 'El-Fettâh', meaning: 'Hayır kapılarını açan, hükmüyle adaleti sağlayan.' },
{ id: '20', arabic: 'الْعَلِيمُ', name: 'El-Alîm', meaning: 'İlmi her şeyi kuşatan.' },
{ id: '21', arabic: 'الْقَابِضُ', name: 'El-Kâbız', meaning: 'Her şeyi teslim alan, hikmeti gereği rızkı ve her türlü nimeti ölçülü veren, eceli gelenlerin ruhlarını teslim alan.' },
{ id: '22', arabic: 'الْبَاسِطُ', name: 'El-Bâsıt', meaning: 'Rızkı ve her türlü rızık imkânını genişleten, ömürleri uzatan.' },
{ id: '23', arabic: 'الْخَافِضُ', name: 'El-Hâfıd', meaning: 'Kâfirleri ve zalimleri alçaltan.' },
{ id: '24', arabic: 'الرَّافِعُ', name: 'Er-Râfi\'', meaning: 'Müminleri yükselten, izzetli ve şerefli kılan.' },
{ id: '25', arabic: 'الْمُعِزُّ', name: 'El-Muizz', meaning: 'Yücelten, güçlü ve aziz kılan.' },
{ id: '26', arabic: 'الْمُذِلُّ', name: 'El-Müzill', meaning: 'Boyun eğdiren, değersiz kılan.' },
{ id: '27', arabic: 'السَّمِيعُ', name: 'Es-Semî\'', meaning: 'Her şeyi işiten.' },
{ id: '28', arabic: 'الْبَصِيرُ', name: 'El-Basîr', meaning: 'Her şeyi gören.' },
{ id: '29', arabic: 'الْحَكَمُ', name: 'El-Hakem', meaning: 'Nihaî hükmü veren.' },
{ id: '30', arabic: 'الْعَدْلُ', name: 'El-Adl', meaning: 'Adaletli, her şeyi yerli yerinde yapan.' },
{ id: '31', arabic: 'اللَّطِيفُ', name: 'El-Latîf', meaning: 'En gizli ve ince hususları dahi bilen, lütufta bulunan, zâtı duyularla algılanamayan, fiillerini rıfk ile gerçekleştiren.' },
{ id: '32', arabic: 'الْخَبِيرُ', name: 'El-Habîr', meaning: 'Gizli ve açık her şeyden haberdar olan, dilediğini haber veren.' },
{ id: '33', arabic: 'الْحَلِيمُ', name: 'El-Halîm', meaning: 'Sabırlı, acele ve kızgınlıkla muamele etmeyen, kudreti olduğu hâlde hemen cezalandırmayan.' },
{ id: '34', arabic: 'الْعَظِيمُ', name: 'El-Azîm', meaning: 'Zât ve sıfatları bakımından pek yüce olan, azametli olan.' },
{ id: '35', arabic: 'الْغَفُورُ', name: 'El-Gafûr', meaning: 'Çok affedici ve bağışlayıcı olan.' },
{ id: '36', arabic: 'الشَّكُورُ', name: 'Eş-Şekûr', meaning: 'Yapılan iyi amellerin karşılığını bolca veren.' },
{ id: '37', arabic: 'الْعَلِيُّ', name: 'El-Aliyy', meaning: 'Yücelik ve hükümranlıkta kendisine eşit veya kendisinden daha üstün bir varlık bulunmayan.' },
{ id: '38', arabic: 'الْكَبِيرُ', name: 'El-Kebîr', meaning: 'Zâtının ve sıfatlarının mahiyeti bilinemeyecek kadar büyük ve ulu olan.' },
{ id: '39', arabic: 'الْحَفِيظُ', name: 'El-Hafîz', meaning: 'Her şey gözetiminde olan, koruyan ve kâinatı dengede tutan.' },
{ id: '40', arabic: 'الْمُقِيتُ', name: 'El-Mukît', meaning: 'Mahlukatın gıdasını yaratıp veren, güç yetiren ve koruyup gözeten.' },
{ id: '41', arabic: 'الْحَسِيبُ', name: 'El-Hasîb', meaning: 'Hesaba çeken, her şeyin neticesini bilen.' },
{ id: '42', arabic: 'الْجَلِيلُ', name: 'El-Celîl', meaning: 'Hiçbir kayıt ve kıyas kabul etmeksizin azamet sahibi, kıymeti ve mertebesi en yüce olan.' },
{ id: '43', arabic: 'الْكَرِيمُ', name: 'El-Kerîm', meaning: 'Çok cömert, nimet ve ihsanı bol olan.' },
{ id: '44', arabic: 'الرَّقِيبُ', name: 'Er-Rakîb', meaning: 'Gözeten, koruyan ve bütün işler murakabesi/kontrolü altında olan.' },
{ id: '45', arabic: 'الْمُجِيبُ', name: 'El-Mücîb', meaning: 'Dua ve dilekleri kabul eden.' },
{ id: '46', arabic: 'الْوَاسِعُ', name: 'El-Vâsi\'', meaning: 'İlmi, rahmeti ve kudreti her şeyi kuşatan.' },
{ id: '47', arabic: 'الْحَكِيمُ', name: 'El-Hakîm', meaning: 'Her işi, emri ve yasağı yerli yerinde olan.' },
{ id: '48', arabic: 'الْوَدُودُ', name: 'El-Vedûd', meaning: 'Müminleri seven ve onlar tarafından da sevilen.' },
{ id: '49', arabic: 'الْمَجِيدُ', name: 'El-Mecîd', meaning: 'Her türlü eksiklikten münezzeh, lütuf ve ikramı bol olan.' },
{ id: '50', arabic: 'الْبَاعِثُ', name: 'El-Bâis', meaning: 'Ölüleri dirilten, peygamberler gönderen.' },
{ id: '51', arabic: 'الشَّهِيدُ', name: 'Eş-Şehîd', meaning: 'Her şeye muttali olan, kendisine hiçbir şey gizli kalmayan.' },
{ id: '52', arabic: 'الْحَقُّ', name: 'El-Hakk', meaning: 'Bizzat ve sürekli olarak var olan, varlığı kendinden olan, uluhiyet ve rububiyeti gerçek olan.' },
{ id: '53', arabic: 'الْوَكِيلُ', name: 'El-Vekîl', meaning: 'Bütün yaratıkların işlerinin görülmesinde güvenilip dayanılan, bu konuda tam yeterli olan.' },
{ id: '54', arabic: 'الْقَوِيُّ', name: 'El-Kavî', meaning: 'Gücü ve kuvveti her şeye yeten.' },
{ id: '55', arabic: 'الْمَتِينُ', name: 'El-Metîn', meaning: 'Âcizliği, zafiyeti ve güçsüzlüğü olmayan, güçlü olan.' },
{ id: '56', arabic: 'الْوَلِيُّ', name: 'El-Velî', meaning: 'Müminlere dost ve yardımcı olan.' },
{ id: '57', arabic: 'الْحَمِيدُ', name: 'El-Hamîd', meaning: 'Çok övülen, bütün övgülere ve övgülerin en yücesine layık olan.' },
{ id: '58', arabic: 'الْمُحْصِي', name: 'El-Muhsî', meaning: 'Gizli ve âşikâr her şeyin ölçü ve sayısını bütün ayrıntılarıyla bilen.' },
{ id: '59', arabic: 'الْمُبْدِئُ', name: 'El-Mübdi\'', meaning: 'Her şeyi yoktan var eden.' },
{ id: '60', arabic: 'الْمُعِيدُ', name: 'El-Muîd', meaning: 'Varlıkları ölümlerinden sonra tekrar yaratan.' },
{ id: '61', arabic: 'الْمُحْيِي', name: 'El-Muhyî', meaning: 'Hayat veren, yaşatan ve dirilten.' },
{ id: '62', arabic: 'الْمُمِيتُ', name: 'El-Mümît', meaning: 'Öldüren, canları kabzeden.' },
{ id: '63', arabic: 'الْحَيُّ', name: 'El-Hayy', meaning: 'Ezelî ve ebedî olarak diri ve ölümsüz olan.' },
{ id: '64', arabic: 'الْقَيُّومُ', name: 'El-Kayyûm', meaning: 'Varlığı kendinden olan, her şeyin varlığı kendisine bağlı olan, kâinatı idare eden.' },
{ id: '65', arabic: 'الْوَاجِدُ', name: 'El-Vâcid', meaning: 'Her şeyi bilen, hiçbir şeye muhtaç olmayan, emrini ve isteğini daima gerçekleştiren.' },
{ id: '66', arabic: 'الْمَاجِدُ', name: 'El-Mâcid', meaning: 'Şânı yüce ve sonsuz kerem sahibi olan.' },
{ id: '67', arabic: 'الْوَاحِدُ', name: 'El-Vâhid', meaning: 'Bir, tek, yegâne varlık; zâtında, ilah ve rab oluşunda ortağı olmayan.' },
{ id: '68', arabic: 'الصَّمَدُ', name: 'Es-Samed', meaning: 'Herkesin kendisine muhtaç olduğu, kendisi ise kimseye muhtaç olmayan, ezelî ve ebedî olan.' },
{ id: '69', arabic: 'الْقَادِرُ', name: 'El-Kâdir', meaning: 'Her şeye gücü yeten.' },
{ id: '70', arabic: 'الْمُقْتَدِرُ', name: 'El-Muktedir', meaning: 'Güç ve kuvvetinde hiçbir sınır olmayan.' },
{ id: '71', arabic: 'الْمُقَدِّمُ', name: 'El-Mukaddim', meaning: 'Hikmeti gereği istediğini öne alan, ileri geçiren.' },
{ id: '72', arabic: 'الْمُؤَخِّرُ', name: 'El-Muahhir', meaning: 'Hikmeti gereği dilediğini geriye bırakan.' },
{ id: '73', arabic: 'الأَوَّلُ', name: 'El-Evvel', meaning: 'Varlığının başlangıcı olmayan, ezelî olan.' },
{ id: '74', arabic: 'الآخِرُ', name: 'El-Âhir', meaning: 'Varlığının sonu olmayan, ebedî olan.' },
{ id: '75', arabic: 'الظَّاهِرُ', name: 'Ez-Zâhir', meaning: 'Varlığını ve birliğini belgeleyen birçok delilin bulunması açısından varlığı açık olan.' },
{ id: '76', arabic: 'الْبَاطِنُ', name: 'El-Bâtın', meaning: 'Zâtı itibarıyla gizli olan, bütün gizlilikleri bilen.' },
{ id: '77', arabic: 'الْوَالِي', name: 'El-Vâlî', meaning: 'Kâinatı yöneten, onlar için gerekli olan her şeyi üstlenen.' },
{ id: '78', arabic: 'الْمُتَعَالِي', name: 'El-Müteâlî', meaning: 'Noksanlıklardan berî, aşkın ve yüce olan.' },
{ id: '79', arabic: 'الْبَرُّ', name: 'El-Berr', meaning: 'Çokça iyilik eden.' },
{ id: '80', arabic: 'التَّوَّابُ', name: 'Et-Tevvâb', meaning: 'Kullarını tövbelerini kabul eden.' },
{ id: '81', arabic: 'الْمُنْتَقِمُ', name: 'El-Müntakım', meaning: 'Suçluları yaptıklarına karşılık cezalandıran.' },
{ id: '82', arabic: 'الْعَفُوُّ', name: 'El-Afüvv', meaning: 'Çokça affeden.' },
{ id: '83', arabic: 'الرَّؤُوفُ', name: 'Er-Raûf', meaning: 'Merhameti ve şefkati çok olan.' },
{ id: '84', arabic: 'مَالِكُ الْمُلْكِ', name: 'Mâlikü\'l-mülk', meaning: 'Mülkün gerçek sahibi, tüm mevcûdâtı idare eden.' },
{ id: '85', arabic: 'ذُو الْجَلاَلِ وَالإِكْرَامِ', name: 'Zü\'l-celâli ve\'l-ikrâm', meaning: 'Sonsuz yücelik ve ikram sahibi olan.' },
{ id: '86', arabic: 'الْمُقْسِطُ', name: 'El-Muksit', meaning: 'Adaleti gerçekleştiren, hakkaniyetle hükmeden.' },
{ id: '87', arabic: 'الْجَامِعُ', name: 'El-Câmi\'', meaning: 'Dünya ve ahirette bütün mahlûkâtı bir araya getirme kudretine sahip olan.' },
{ id: '88', arabic: 'الْغَنِيُّ', name: 'El-Ganî', meaning: 'Hiçbir şeye ihtiyacı olmayan.' },
{ id: '89', arabic: 'الْمُغْنِي', name: 'El-Muğnî', meaning: 'İhtiyaçtan kurtaran zengin kılan.' },
{ id: '90', arabic: 'الْمَانِعُ', name: 'El-Mâni\'', meaning: 'Hikmeti gereği engel koyan, mâni olan.' },
{ id: '91', arabic: 'الضَّارُّ', name: 'Ed-Dârr', meaning: 'Hikmeti gereği elem ve zarar verici şeyleri yaratan.' },
{ id: '92', arabic: 'النَّافِعُ', name: 'En-Nâfi\'', meaning: 'Hayrı ve faydayı yaratan ve veren.' },
{ id: '93', arabic: 'النُّورُ', name: 'En-Nûr', meaning: 'Nurlandıran, her şeyi aydınlatan, kalplere nur ve iman veren.' },
{ id: '94', arabic: 'الْهَادِي', name: 'El-Hâdî', meaning: 'Doğru yolu gösteren, hidâyete erdiren.' },
{ id: '95', arabic: 'الْبَدِيعُ', name: 'El-Bedî\'', meaning: 'Örneksiz ve benzersiz olarak yoktan yaratan.' },
{ id: '96', arabic: 'الْبَاقِي', name: 'El-Bâkî', meaning: 'Varlığı sürekli olan, ebedî, sonsuz olan.' },
{ id: '97', arabic: 'الْوَارِثُ', name: 'El-Vâris', meaning: 'Varlığının sonunun bulunmaması vasfıyla kâinatın gerçek sahibi.' },
{ id: '98', arabic: 'الرَّشِيدُ', name: 'Er-Reşîd', meaning: 'Yol gösteren, her işi isabetli olan.' },
{ id: '99', arabic: 'الصَّبُورُ', name: 'Es-Sabûr', meaning: 'Günahkârları hemen cezalandırmayıp onlara mühlet tanıyan.' },
];